### ISSUE TITLE
Visicalc Advanced does not boot

### ISSUE THREAD

**Issue by timriker** [ct6502/apple2ts#69] opened 2024-05-22 20:52 UTC
This works:

https://www.scullinsteel.com/apple/e#https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/spreadsheet/Visicalc%20Advanced.po

but this does not:

https://apple2ts.com/#https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/spreadsheet/Visicalc%20Advanced.po

Is this an 800k floppy issue or something else?

**Comment by ct6502** [comment] 2024-05-22 22:07
Hmm, it seems to work for me when I just tried it? It takes a few seconds for it to download the file and then start up, but afterwards it seems fine. I tried on MacOS on both Safari and Chrome.
![Screenshot 2024-05-22 at 4 06 27 PM](https://github.com/ct6502/apple2ts/assets/5461379/d6de65bd-1a0c-4e75-b290-4916dd4a18c4)

**Comment by timriker** [comment] 2024-05-22 23:24
Hmm. Works for me on another system. Might be filtering something on my work computer. Go ahead and close this. Sorry. Thanks for all you do!

**Comment by ct6502** [comment] 2024-05-23 02:15
Closing, unable to reproduce. Let me know if you find out anything more. And thanks for logging bugs!

**Closed by ct6502** 2024-05-23 02:15 UTC
Labels: bug

**Comment by timriker** [comment] 2024-05-23 04:11
Just to follow through, my work computer is redirecting the proxy.cors.sh request to opendns and blocking it. My home pc loads it just fine. The iijs instance loads the image directly which works fine.

**Comment by ct6502** [comment] 2024-05-23 13:30
Yes, I wondered if it was a proxy cors problem. That whole cors issue is a pain, but it’s the only way that I know to load content from a completely different website. I don’t understand how iijs does it - maybe they have a backend server or their own cors that is not getting blocked. I don’t understand cors enough to know if there are more clever ways to do this. Thanks for the followup!

On May 22, 2024, at 10:11 PM, Tim Riker ***@***.***> wrote:


Just to follow through, my work computer is redirecting the proxy.cors.sh request to opendns and blocking it. My home pc loads it just fine. The iijs instance loads the image directly which works fine.
